version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: ev_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"               # change left side if 5432 is busy, e.g. "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sql
      POSTGRES_DB: ev_project
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ev_project"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

    
